### ISSUE TITLE
Only works when Autorotate is enabled (Android)

### ISSUE THREAD

**Issue by nathansamson** [rmtmckenzie/flutter_native_device_orientation#1]
I know, when autorotate is disabled I should not rotate.

But there is one use case where this is still valid: Displaying a fullscreen (video). In fact this is also what the official youtube app does (and some others as well)

**Comment by rmtmckenzie** [comment]
Ah. Yeah this probably wouldn't do that, as it's really only reporting which direction the 'window' on the screen is facing. I'd have to look into how I could report that - it'd probably mean watching the actual orientation of the device (angle etc) and deciding what to report based on that.

Unfortunately, that would break the use-case I have for this plugin which relies on it reporting based on the window orientation... Maybe it could be a configuration option.

Is this something you need?

**Comment by nathansamson** [comment]
As explained this is something I would like for my app. But maybe you are right that this plugin is not the right location for this.

I will explain my use case a bit better.
I have a screen where I play a video + other info is on the screen.
When the user fullscreens the video I want all other content to disappear and the video to be displayed in landscape mode regardless on how the phone is held (as just displaying the video in keeping aspect ratio in portrait mode will actually not make it bigger which is the goal)
The video should display correctly regardless if the user holds the phone "landscape left" or "landscape right" (if he still keeps it portrait up/down we have to make an arbitrary choice)

This is the same behaviour as the youtube app uses when fullscreening a video even when autorotate is disabled (it is always disabled on my phone as I generally dislike it).

**Comment by rmtmckenzie** [comment]
Okay cool. Yeah I might be able to add in an option for that - it could be a different plugin but it seems slightly silly to have two seperate plugins for only very slightly different use-cases. Not sure when I'll get a chance, PRs are always welcome though.

FYI - in android P there's a new feature where if you have autorotate disabled and turn your phone an icon shows up in the bottom bar that you can press to manually rotate. Something to look forward to =)

**Comment by nathansamson** [comment]
I am happy to provide a pr, if you can hint me in the right direction of native APIs to use

I am new to flutter in specific and mobile development in general :)

The Android p feature sounds cool but won't fix the issue for a while :)

**Comment by rmtmckenzie** [comment]
Okay. Hmm. Well this might be slightly complicated, but I can definitely point you in _a_ direction =D.  It shouldn't require a whole lot of code though.

Take a look at [this stack overflow answer](https://stackoverflow.com/questions/15871664/get-device-rotation-when-auto-rotate-is-off) - it should tell you what you need to do more or less on the android side. Basically, instead of listening to the window's orientation change stuff, you listen for orientation directly from the sensor. I'd make a class that does this (similar to the OrientationListener in my existing code) that can stop and start listening.  You can probably re-use the OrientationCallback I've defined as well.

What I'd do is make an interface called IOrientationListener that has the start/stop methods defined and that the OrientationListener and SensorOrientationListener implement, and keep a reference to that in the Plugin class. That way you can pretty much leave the existing code plugin code as-is except an if-else deciding which listener to make.

The big difference is that now instead of simply returning the value from the listener, you actually have to calculate the position of the phone based on the orientation (but that's also included in the stack overflow answer).

I'd just add a boolean flag to the constructor of the helper class & communication methods on the dart side something along the lines of 'useSensor', which should default to false.

Let me know how it goes and if you get stuck! I may be able to find time at some point this week to look into this though, as it doesn't seem like as large a task as it did before I looked into it a bit.

**Comment by SemonCat** [comment]
Any update for this issue?

**Comment by rmtmckenzie** [comment]
I never ended up getting around to looking into this more. I don't think I'll have any time this week, possibly next week...

**Comment by desmese** [comment]
I needed this for a project as well, so I started working on it. I am able to retrieve the device orientation and sent it back. The only thing I still need to implement is the ability to pass the 'useSensor' parameter to the Constructor. Since this is my first Flutter plugin I am working on I have to find out the best way to implement it. Once this is implemented I will create a pull-request. The current progress can be found in my fork: https://github.com/desmese/flutter_native_device_orientation

**Comment by desmese** [comment]
#3 I have created a pull-request to resolve this issue for Android. If you have any questions, let me know.

**Comment by rmtmckenzie** [comment]
Hey thanks for the pull request on this. I've been pretty busy and now on holidays for a bit and haven't had a chance to merge it but I'll try to do that next week once I'm back.

**Comment by desmese** [comment]
@rmtmckenzie Ok thanks, enjoy your holiday!

**Comment by analogic** [comment]
I was going to implement same solution and found this PR. Awesome work @desmese ! Already using your fork.

**Comment by rmtmckenzie** [comment]
Just pushing the update in a minute. Thanks for the PR!

**Comment by desmese** [comment]
@rmtmckenzie You're welcome. Thanks for merging it!
