### ISSUE TITLE
Landscape Left/Right are Reversed

### ISSUE THREAD

**Issue by rzagelow** [rmtmckenzie/flutter_native_device_orientation#11]
The landscape left and landscape right orientations reported by this plugin are reversed when compared to Apple's definition. This wouldn't be a big deal except I'm trying to use this plugin with another plug that has them correct and it is causing a conflict. See images below. I'm happy to try to do a PR if you don't have the time to resolve. Thanks!

<img width="776" alt="auto_orientation" src="https://user-images.githubusercontent.com/7141163/60038201-87c34f80-9668-11e9-84e6-58b9f1d849b0.png">

![iphone_orientations](https://user-images.githubusercontent.com/7141163/60038150-58acde00-9668-11e9-8c9b-130ee8a67668.png)

**Comment by rmtmckenzie** [comment]
That is actually by design, both because it is consistent with Android and because what apple did makes absolutely no sense (they say it's called "Landscape Left" because you have to turn the device left to get back to natural... which I suppose might make sense if you're trying to purposefully alienate everyone else who has ever used orientation on any other platform ever. _Sigh_. Well okay that might be an exaggeration, but I still find it counterintuitive). 

I actually originally had the plugin return that for iOS and received the feedback that it was confusing that the two platforms worked differently, so I figured the plugin might as well be consistent.

If you want to do a PR you could, but I'd ask you to put it behind a flag something "useIOSOrientations" and make sure that it works properly for both when useSensor = true and useSensor = false.

It may be easier just to wrap the onOrientationChanged with a `() => switch(orientation) { case ...Left: return ...Right; case ...Right: return ...Left: default: return orientation;}` though.
