### ISSUE TITLE
qr_mobile_vision cannot build 

### ISSUE THREAD

**Issue by radvansky-tomas** [rmtmckenzie/flutter_native_device_orientation#21]
```
Undefined symbols for architecture i386:
  "_FlutterMethodNotImplemented", referenced from:
      -[NativeDeviceOrientationPlugin handleMethodCall:result:] in NativeDeviceOrientationPlugin.o
  "_OBJC_CLASS_$_FlutterEventChannel", referenced from:
      objc-class-ref in NativeDeviceOrientationPlugin.o
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in NativeDeviceOrientationPlugin.o
ld: symbol(s) not found for architecture i386
```

![image](https://user-images.githubusercontent.com/12473664/87871082-bd6c7080-ca01-11ea-8d93-038e9341ebaa.png)

**Comment by rmtmckenzie** [comment]
I removed the auto-generated part of the podfile that explicitly blocked i386, but I don't think that's going to help - if you're building for i386 architecture it's going to fail at some point because Flutter support it. So hopefully that is fixed in 0.4.2 but your underlying issue isn't anything to do with this plugin. I think this issue is related: https://github.com/flutter/flutter/issues/17749

**Comment by radvansky-tomas** [comment]
The plugin `native_device_orientation` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

**Comment by rmtmckenzie** [comment]
Oops, I accidentally removed the old embedding method. You should probably upgrade to the new version at some point but I've re-added it.
