### ISSUE TITLE
New API for the angle of rotation of the device

### ISSUE THREAD

**Issue by stepushchik-denis** [rmtmckenzie/flutter_native_device_orientation#24]
Hello! Thanks for plugin.
Can you please add the ability to get the angle of rotation of the device? This would be very useful for custom orientation logic.

API can be something like that:
```
// angle in radian
Stream<double> onRotationAngleChanged() {
}
```

**Comment by rmtmckenzie** [comment]
I've purposefully avoided exposing that as there's a package that already does that - the [sensors package](https://pub.dev/packages/sensors). Also because rotation is very subjective - I'd essentially be having to write an algorithm to describe the rotation of the device from the 3 dimensional coordinates to a simple rotation, which I'd like to avoid. There's something in there for the 'useSensor' parameter, but it's honestly pretty subpar at the moment.
